import type { Metadata } from "next";
import { Poppins, Montserrat} from "next/font/google";

import "./globals.css";
import Navbar from "./components/Navbar";

const poppins = Poppins({
 subsets:["latin"],
 variable:'--font-poppins',
 weight: ['300', '400', '500', '600'],
 display: 'swap'
})
const montserrat = Montserrat({
 subsets:["latin"],
 variable:'--font-montserrat',
 display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased  ${poppins.variable} ${montserrat.variable}`}
      >
          <Navbar />
        <main className="mx-20">
    
        {children}
        </main>
  
      </body>
    </html>
  );
}
